# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ebayKoRnStarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ebayKoRnStarter
  pod 'Firebase/Core'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  #pod 'Firebase/AdMob'
  #pod 'Firebase/Crash'
  #pod 'Firebase/Database'
  #pod 'Firebase/DynamicLinks'
  #pod 'Firebase/Performance'
  #pod 'Firebase/Messaging'
  #pod 'Firebase/RemoteConfig'
  #pod 'Firebase/Storage'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
